name: Typst PDF build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Rust und Cargo installieren
      uses: dtolnay/rust-toolchain@stable

    - name: Typst installieren
      run: cargo install --locked typst-cli

    - name: PDF kompilieren
      run: typst compile main.typ

    - name: Ã„nderungen committen und pushen
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add main.pdf
        git commit -m "Auto-update PDF"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
      continue-on-error: true