name: Typst PDF build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Rust und Cargo installieren
      uses: dtolnay/rust-toolchain@stable

    - name: Typst installieren
      run: cargo install --locked typst-cli

    - name: PDF kompilieren
      run: typst compile main.typ out.pdf

    - name: PDF ins Repo kopieren
      run: cp out.pdf main.pdf

    - name: Ã„nderungen committen und pushen
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add main.pdf
        git commit -m "Auto-update PDF"
        git push
      continue-on-error: true